from tkinter import *
import os
import subprocess

root = Tk()
theLabel = Label(root, text="Folow the putun please")
theLabel.pack()
top= Frame(root)
top.pack()
bottomFrame =Label(root)
bottomFrame.pack(side=BOTTOM)
photo=PhotoImage(file="ind.png")
theLabel=Label(root, image=photo)
theLabel.pack()

button1=Button(top, text="Record" , fg="red" , command=list)
button2=Button(top, text="Power" , fg="red")
button3=Button(top, text="Must" , fg="red")
button4=Button(top, text="1" , fg="red")
button5=Button(top, text="2" , fg="red")
button6=Button(top, text="3" , fg="red")
button7=Button(top, text="4" , fg="red")
button8=Button(top, text="5" , fg="red")
button9=Button(top, text="6" , fg="red")
button10=Button(top, text="7" , fg="red")
button11=Button(top, text="8" , fg="red")
button12=Button(top, text="9" , fg="red")
button13=Button(top, text="0" , fg="red")
button14=Button(top, text="up" , fg="red")
button15=Button(top, text="down" , fg="red")
button16=Button(top, text="left" , fg="red")
button17=Button(top, text="right" , fg="red")
button18=Button(top, text="OK" , fg="red")
button19=Button(top, text="MENU" , fg="red")
button20=Button(top, text="EXIT" , fg="red")
button23=Button(top, text="BACK" , fg="red")

button21=Button(top, text="press to enter the name of butun" , fg="blue")
button22=Button(bottomFrame, text="end Record" , fg="green" ,command=bottomFrame.quit)
button1.pack()
button2.pack()
button3.pack()
button4.pack()
button5.pack()
button6.pack()
button7.pack()
button8.pack()
button9.pack()
button10.pack()
button11.pack()
button12.pack()
button13.pack()
button14.pack()
button15.pack()
button16.pack()
button17.pack()
button18.pack()
button19.pack()
button20.pack()
button21.pack()
button22.pack()
button23.pack()

root.mainloop()
